### ISSUE TITLE
Remove PartnerEventBus section

### ISSUE THREAD

**Issue by gfinocchiaro** [aws-samples/amazon-eventbridge-partnerevent-example#3]
Linking AWS with an EventBridge partner as MongoDB Atlas creates an event bus, which only needs to be referenced in the event rule section but not created, as specified in the PartnerEventBus.

So, to make the example works the following section should be removed:

```yaml
  PartnerEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
      EventSourceName: !Ref PartnerEventSource
      Name: !Ref PartnerEventSource
```
